#! /bin/sh
#=======================================================#
#  _   _             _   ____                           #
# | | | |_ __   __ _| | | __ )  __ _ _ __ _   _  __ _   #
# | | | | '_ \ / _` | | |  _ \ / _` | '__| | | |/ _` |  #
# | |_| | |_) | (_| | | | |_) | (_| | |  | |_| | (_| |  #
#  \___/| .__/ \__,_|_| |____/ \__,_|_|   \__,_|\__,_|  #
#       |_|                                             #
#=======================================================#

# BSPWM CONFIGURATION --------------------------------------------------------------------------------------------------------
bspc monitor -d I II III IV V VI
pgrep -x sxhkd > /dev/null || sxhkd &
picom -b --experimental-backends &
latte-dock --layout kbspwm &

bspc config border_radius                 0
bspc config border_width                  1
bspc config window_gap                    7

bspc config top_padding                   30
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0

bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# BSPWM COLORS --------------------------------------------------------------------------------------------------------------- 
bspc config normal_border_color "#44475a"
bspc config active_border_color "#6272a4"
bspc config focused_border_color "#C0C0C0"
bspc config presel_feedback_color "#6272a4"

# BSPWM RULES ---------------------------------------------------------------------------------------------------------------- 
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a plasmashell state=floating border=off sticky=off center=off
bspc rule -a krunner state=floating border=off sticky=off center=on
